language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

install:
  - composer install
  - pecl install runkit

script:
  - phpunit --coverage-text --process-isolation --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
